### ISSUE TITLE
Unable to run openutau on linux

### ISSUE THREAD

**Issue by la1den** [xunmengshe/OpenUtau#53]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

Unable to run openutau on linux
```
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Base/Media/FontManager.cs:line 37
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Base/Media/FontManager.cs:line 59
   at Avalonia.Media.Typeface.get_GlyphTypeface() in /_/src/Avalonia.Base/Media/Typeface.cs:line 87
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 58
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/Compositor.Factories.cs:line 17
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 53
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/TopLevel.cs:line 188
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/WindowBase.cs:line 55
   at Avalonia.Controls.Window..ctor(IWindowImpl impl) in /_/src/Avalonia.Controls/Window.cs:line 223
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 214
   at OpenUtau.App.Views.MainWindow..ctor() in /home/runner/work/OpenUtau/OpenUtau/OpenUtau/Views/MainWindow.axaml.cs:line 47
   at OpenUtau.App.App.OnFrameworkInitializationCompleted() in /home/runner/work/OpenUtau/OpenUtau/OpenUtau/App.axaml.cs:line 34
   at Avalonia.AppBuilder.SetupUnsafe() in /_/src/Avalonia.Controls/AppBuilder.cs:line 307
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 291
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 219
   at OpenUtau.App.Program.Main(String[] args) in /home/runner/work/OpenUtau/OpenUtau/OpenUtau/Program.cs:line 41
zsh: IOT instruction (core dumped)  ./OpenUtau
```

### Explains how to reproduce the bug

1 download and unzip [OpenUtau-linux-x64-0.1.158.22.zip](https://github.com/xunmengshe/OpenUtau/releases/download/0.1.158.22/OpenUtau-linux-x64-0.1.158.22.zip)
2 double click or run in terminal
3 then double-clicking does not have any antisense, and the prompt crashes when running in the command line

### OS & Version

Arch Linux / Linux 6.1.39-2-lts x86_64 rolling n/a

### Logs

No log found

**Comment by la1den** [comment]
Setting `LANG` to `C` solves the problem.

**Comment by SoulMelody** [comment]
Here is a solution from steamtools [Avalonia font manager patch](https://github.com/BeyondDimension/SteamTools/issues/827)

**Comment by la1den** [comment]
The latest version is functioning properly.
